In [20]:
import numpy as np

from elucid.geometry import frame

## Coordinate Systems

For the details of how to convert between the J2k observation coordinates and the simulation coordinates (i.e. $x \in [0, L)^3$, where L=500 Mpc/h), see 
Data Specification in the README of this repository.

Below are examples.

In [21]:
frame = frame.SimFrameSdssL500()

Here are the simulation coordinates (in $h^{-1}{\rm Mpc}$) of some known 
galaxy clusters

In [22]:
x_sims = np.array([
    [332.63, 318.91, 63.53],       # Coma (Abell 1656)
    [321.13, 335.49, 51.64],       # Leo (Abell 1367)
    [254.91 , 221.74 , 44.49],     # Abell 1630
    [215.07, 198.16, 38.16],       # Abell 1564 
])

Find their J2K (Cartesian) coordinates:

In [23]:
x_j2ks = frame.pos_sim_to_j2k(x_sims)
x_j2ks

array([[ -61.19392336,  -16.18668416,   33.53      ],
       [ -59.69696983,    3.93558038,   21.64      ],
       [-182.74476988,  -42.79117644,   14.49      ],
       [-228.54563981,  -36.04415383,    8.16      ]])

Convert J2K Cartesian coordinates to RA, Dec (both in degree), redshift:

In [24]:
ras, decs, zs = frame.pos_j2k_to_ra_dec_z(x_j2ks)
for ra, dec, z in zip(ras, decs, zs):
    print(f"RA: {ra:.3f} deg, Dec: {dec:.3f} deg, z: {z:.5f}")

RA: 194.816 deg, Dec: 27.911 deg, z: 0.02401
RA: 176.228 deg, Dec: 19.886 deg, z: 0.02131
RA: 193.179 deg, Dec: 4.415 deg, z: 0.06359
RA: 188.962 deg, Dec: 2.020 deg, z: 0.07844


Convert them back to J2K coordinates:

In [25]:
x_j2ks = frame.pos_ra_dec_z_to_j2k(ras, decs, zs)
x_j2ks

array([[ -61.20606901,  -16.18989686,   33.53665497],
       [ -59.70329613,    3.93599745,   21.64229327],
       [-182.75836651,  -42.7943602 ,   14.49107809],
       [-228.55359101,  -36.04540782,    8.16028389]])

and then back to simulation coordinates:

In [26]:
x_sims = frame.pos_j2k_to_sim(x_j2ks)
x_sims

array([[332.62258287, 318.89985976,  63.53665497],
       [321.12482107, 335.48634285,  51.64229327],
       [254.90143704, 221.72896912,  44.49107809],
       [215.06460992, 198.15402161,  38.16028389]])